name: Debug Poetry Installation

on:
  workflow_dispatch:  # Manual trigger only
  
jobs:
  debug-poetry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Debug Python environment
      run: |
        python --version
        pip --version
        which python
        python -m pip list
    
    - name: Install Poetry manually (fallback method)
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      
    - name: Verify Poetry installation
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry --version
        poetry config --list
    
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry install --no-interaction
    
    - name: Run basic tests
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry run python --version
        poetry run python -c "import secret_guardian; print('✅ Package imported successfully')"
        poetry run python -m secret_guardian --help
